source 'https://rubygems.org'

#OSM api client
gem 'rosemary', '0.4.4'

#JSON object parser
gem 'json', '1.8.3'

#HTML Sanitizer
gem 'sanitize', '4.0.1'

#HTTParty REST simple lib
gem 'httparty', '0.11.0'

#Haversine distance
gem 'haversine', '0.3.0'

#Testing gem
gem 'test-unit', '3.1.5'

#Unit test complemet
gem 'test-unit-full', '0.0.3'

#Testing coverage tool
gem 'simplecov', '0.10.0'



